#! /usr/bin/env pwsh

#Show "help" page as default script, it also contains the server and cluster values.
param(
    [string]$script = "help",
    [switch]$docker,
    [ValidateSet("127.0.0.1", "Server1", "Server2")]
    [string]$server,
    [ValidateSet("DC0_C0", "Cluster2", "Cluster3")]
    [string]$cluster,
    [switch]$help
)

#Utils.ps1 contains all the defined functions
.(".\src\utils.ps1")

if ($script -eq "help" -Or $help) {
    .(".\src\help.ps1")    
    exit 0
}

if ($docker -eq "./src/docker" -Or $docker) {
    Ensure-Docker-Installed
    Docker-Start-Settings
    Write-Host "CIAO DOCKER"

    Exit 0
}

    Ensure-Path-Exists

    Ensure-Server-Set

    Ensure-Cluster-Set

    #Normalize user input removing the extension .ps1
    $script = Normalize-Script-Name -Script $script

    Ensure-Script-Exists -Script $script -AvailableScripts $AvailableScripts

    .(".\scripts\$script.ps1")






